apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://shaikhshayan137:<pass>@cluster0.joqu9jg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
