apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://shaikhshayan137:xu4QfRicrdK7u1MA@cluster0.joqu9jg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
